stock_name   : ^GSPC
window_size  : 10
episode_count: 500
result_dir   : ./models/config

batch_size: 32

clip_reward   : True
reward_for_buy: -10
gamma         : 0.995
learning_rate : 0.001
optimizer     : Adam